# Generated by Django 6.0.5 on 2026-05-22 13:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('intitule', models.CharField(max_length=200)),
                ('seuil_presence_pct', models.PositiveSmallIntegerField(default=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('STUDENT', 'Étudiant'), ('TEACHER', 'Enseignant'), ('ADMIN', 'Administrateur'), ('SUPER_ADMIN', 'Super Administrateur')], default='STUDENT', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='ZoneGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('rayon_m', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone GPS',
                'verbose_name_plural': 'Zones GPS',
                'db_table': 'zone_gps',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('statut', models.CharField(choices=[('PLANIFIÉE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINÉE', 'Terminée'), ('ANNULÉE', 'Annulée')], default='PLANIFIÉE', max_length=12)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.module')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_creees', to='api.utilisateur')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='api.zonegps')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('precision_gps_m', models.FloatField(blank=True, null=True)),
                ('distance_zone_m', models.FloatField(blank=True, null=True)),
                ('is_offline_sync', models.BooleanField(default=False)),
                ('offline_sync_at', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('VALIDE', 'Valide'), ('HORS_ZONE', 'Hors zone'), ('REJETÉ', 'Rejeté')], default='VALIDE', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointages', to='api.session')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointages', to='api.utilisateur')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'db_table': 'pointage',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='enseignant',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.PROTECT, related_name='modules_enseignes', to='api.utilisateur'),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.module')),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.utilisateur')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'db_table': 'inscription',
            },
        ),
        migrations.CreateModel(
            name='AlerteFraude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fraude', models.CharField(choices=[('hors_zone', 'Hors zone GPS'), ('doublon', 'Pointage en double'), ('coords_fixes', 'Coordonnées GPS fixes'), ('heure_invalide', 'Heure hors session'), ('autre', 'Autre')], max_length=20)),
                ('score_ia', models.FloatField(blank=True, null=True)),
                ('niveau_severite', models.CharField(blank=True, choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ÉLEVÉ', 'Élevé'), ('CRITIQUE', 'Critique')], max_length=10, null=True)),
                ('statut', models.CharField(choices=[('NON_TRAITÉE', 'Non traitée'), ('EN_INVESTIGATION', 'En investigation'), ('FRAUDE_CONFIRMÉE', 'Fraude confirmée'), ('FAUSSE_ALERTE', 'Fausse alerte')], default='NON_TRAITÉE', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('traite_at', models.DateTimeField(blank=True, null=True)),
                ('pointage', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='alerte_fraude', to='api.pointage')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitees', to='api.utilisateur')),
            ],
            options={
                'verbose_name': 'Alerte Fraude',
                'verbose_name_plural': 'Alertes Fraude',
                'db_table': 'alerte_fraude',
            },
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['session', 'timestamp'], name='idx_pointage_session_ts'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['utilisateur', 'session'], name='idx_pointage_user_session'),
        ),
        migrations.AddConstraint(
            model_name='pointage',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'VALIDE')), fields=('utilisateur', 'session'), name='unique_pointage_valide_par_session'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('etudiant', 'module'), name='unique_inscription_etudiant_module'),
        ),
        migrations.AddIndex(
            model_name='alertefraude',
            index=models.Index(fields=['statut', 'timestamp'], name='idx_alerte_statut_ts'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('module', 'zone', 'date', 'heure_debut', 'heure_fin'), name='unique_session_module_zone_creneau'),
        ),
    ]
