# Generated by Django 6.0.5 on 2026-05-26 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertefraude',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inscription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pointage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='zonegps',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='pointage',
            name='unique_pointage_valide_par_session',
        ),
        migrations.AlterField(
            model_name='alertefraude',
            name='niveau_severite',
            field=models.CharField(blank=True, choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alertefraude',
            name='statut',
            field=models.CharField(choices=[('NON_TRAITEE', 'Non traitée'), ('EN_INVESTIGATION', 'En investigation'), ('FRAUDE_CONFIRMEE', 'Fraude confirmée'), ('FAUSSE_ALERTE', 'Fausse alerte')], default='NON_TRAITEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='api.utilisateur'),
        ),
        migrations.AlterField(
            model_name='module',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules_enseignes', to='api.utilisateur'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='statut',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('HORS_ZONE', 'Hors zone'), ('REJETE', 'Rejeté')], default='VALIDE', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='statut',
            field=models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULEE', 'Annulée')], default='PLANIFIE', max_length=12),
        ),
    ]
